language: python
rvm:
- 2.2.0
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y python-lxml python-pip
install:
- deactivate
- sudo pip install xml2rfc
script:
- make ghpages
env:
  global:
  - secure: GnggxmmxFwLjszsuQROYyB9WF0YtIbEN/K5znQ2Lj8uj5z0gn/eKcF3Dn2ecOgJ5jeuDjQgYnG+lBpheFo29KczrVgzlLygd/C+z+1pn4H1g96API1bhZc1x+ujlUphK8MezM3YVI0cI9ixfULg6aZK8V6qVbQySBKsU2R4PMiDB8Y9brWW1mc5XSsNXjucBRUPOaEK6/JtVAph5IKiuZw0DW4B+Aj0+yPQcSLqXIr5W818WCp7f4yRaROd6RaTO8tvpsgwJhrIXKEeedvNRV1vkn5u98NYWP/IkKszYh1q3uZ0/7mnRnZYvRRdVpKOutZX5WRpQRG1brccPark/gtxwmLBCWsZGEvWwtSfLuAv7XjCAh0wGSI5zCRj1o0HfBKdKBiH9Vqc64A6b3NjSdJgjIP+nKHnlYZDqmb4auwXkdHhm/QqGvIwueDozhW1YwgkR5EeEzRZW/21ZW8HkXY/A0RqfFWjrtMUGwHyH7Ht8PcsMHtHKm/HVpRd/I1hE2SIt1VBsi9ZkQRzaYh6S3yRLS0e/0AQsC8M+FPsn9V0LQduVTzhLEJKqPsNEzj8IKnVWdcJ+9T6kUVFY1eJuPqyANG+iM+dODddduMgG97mOn9/1Og1aCDGqCYJligzf9pTZz+yfADQSi5hxJ3NwRTDXxePvD9cPnD2+DnXwS8Y=
before_deploy: make submit
deploy:
  provider: releases
  api-key:
    secure: <Fill in>
  file:
  - "$TRAVIS_TAG.txt"
  - "$TRAVIS_TAG.html"
  - "$TRAVIS_TAG.xml"
  skip_cleanup: true
  on:
    branch: master
    tags: true
